version: '3.8'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
    stdin_open: true
    tty: true
